server:
  port: 5000
  contextPath: '/authorization'

authorization-server:
  jwt:
    privateKeyFile: 'authorization-service/src/main/resources/key'
    publicKeyFile: 'authorization-service/src/main/resources/key.pub'


security:
  oauth2:
    resource:
      jwt:
        keyValue: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJSrJ00wVYt/wOGa7VaI+50SXIt1nsTSgZKY4YdxkwMWjBWo2QCPO62bTl/w1RnyFTtPBg+7VvGr784p1ul2M9WAiGh2OOaWPh8Q7gUuvDIveGOqy8YtV2gdADNo7xNJtc9VEjI+EEoCQ8FghBkts7ah6d5SMk5J67iT3o1uNkvVw3zVgH3AJluUgFmvChX5mtXNz5cHR3sBDoncWSFGrLO9O5ZXIUspEZDKcoj906kP/jrzX4txvveHgvHlLLkjmwUJewPLG0TTrMC5/5mO5S0JC4nqrJpSaRETcv2szt1mAMrMt5qO/2VpoPbfe8AEovxj5dClGgvFTpsDbanCT9 timobejan@Timos-MacBook-Pro.local


facebook:
  client:
    clientId: 249465598776862
    clientSecret: eb4b9ed69ee9417f02ab001f8828760e
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    scope: ['email','user_about_me']
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=first_name,last_name,email
google:
  client:
    clientId: 432080264705-gui89diklp7fopr32is5i2d352ql6f0u.apps.googleusercontent.com
    clientSecret: pnzWfXswP5YBnpPbpTOg_Dh3
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: authorization_code
    authenticationScheme: query
    scope: https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo


spring:
    datasource:
        url: jdbc:mysql://mysql-authorization/authorization
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        hibernate.ddl-auto: update
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect